version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  e2e-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-jammy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
      - run:
          name: Install Playwright Browsers
          command: |
            npx playwright install --with-deps
      - run:
          name: Run Playwright tests
          command: |
            npx playwright test
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - e2e-playwright
